blueprint:
  name: Room Automation - Activity
  domain: automation
  input:
    room:
      name: Room
      selector:
        area:

    activity_scene:
      name: Activity Scene
      default: []
      selector:
        entity:
          domain: scene

    activity_sensor:
      name: Activity Sensor
      default: []
      selector:
        entity:
          domain: binary_sensor

mode: restart

trigger:
  - platform: state
    id: activity_sensor_on
    entity_id: !input activity_sensor
    to: "on"

variables:
  room: !input room
  sensor: 'binary_sensor.{{room}}'
  manual_switch: 'input_boolean.{{ room }}'

condition:
  - "{{ is_state(sensor, 'on') }}"
  - "{{ is_state(manual_switch, 'off') }}"
  - "{{ not is_state('media_player.' + room + '_tv', 'on') }}"

action:
  - service: scene.turn_on
    target:
      entity_id: !input activity_scene    
    data:
      transition: 1
